lint:
  files_unchanged:
    - assets/nf-core-metatdenovo_logo_light.png
    - docs/images/nf-core-metatdenovo_logo_light.png
nf_core_version: 3.3.1
repository_type: pipeline
template:
  author: Danilo Di Leo, Emelie Nilsson & Daniel Lundin
  description: Assembly and annotation of metatranscriptomic data, both prokaryotic
    and eukaryotic
  force: false
  is_nfcore: true
  name: metatdenovo
  org: nf-core
  outdir: .
  version: 1.1.2
