name: "unpigz"
description: Decompresses gzipped files using pigz
keywords:
  - unpigz
  - decompress
  - gunzip
  - pigz
input:
  meta:
      type: map
      description: Groovy Map containing sample information
  file:
      type: file
      description: Gzipped input file
      pattern: "*.gz"
output:
  meta:
      type: map
      description: Groovy Map containing sample information
  unzipped:
      type: file
      description: Decompressed output file
      pattern: "*"
  versions_pigz:
    - - "${task.process}":
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - "${task.process}":
          type: string
          description: The name of the process
      - pigz:
          type: string
          description: The name of the tool
      - pigz --version 2>&1:
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@danilodileo"
