name: "hmmclassify"
description: Performs HMM-based classification using HMMER and ranks the results
keywords:
  - hmm
  - classification
  - protein
  - hmmer
  - ranking
components:
  - hmmer/hmmsearch
  - hmmrank
  - seqtk/hmmhitfaas
input:
  - ch_hmmclassify:
      type: tuple
      description: Channel containing metadata, HMM file, and amino acid FASTA file
      pattern: "[ val(meta), [ hmm, aa_fasta ] ]"
output:
  - hmmrank:
      type: file
      description: Ranked HMM search results
      pattern: "*.hmmrank.tsv.gz"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@danilodileo"
